
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-platform-demo.fullname" . }}
  labels:
    app: {{ include "ai-platform-demo.name" . }}
    {{- include "ai-platform-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "ai-platform-demo.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
