
{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ai-platform-demo.fullname" . }}
  labels:
    release: {{ .Values.monitoring.serviceMonitor.prometheusReleaseLabel }}
spec:
  selector:
    matchLabels:
      app: {{ include "ai-platform-demo.name" . }}
  namespaceSelector:
    any: true
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
{{- end }}
